name: census logistic regression model

on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out actions
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.8
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.8
